create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null default 'Guest',
  text text not null,
  created_at timestamptz not null default now()
);
alter table public.messages enable row level security;
create policy "Anyone can read messages" on public.messages for select using (true);
create policy "Anyone can send messages" on public.messages for insert with check (char_length(text) between 1 and 500);
alter publication supabase_realtime add table public.messages;
